[package]
name = "noteberg"
version = "0.2.1"
description = "A note-taking app supporting handwritten notes, text, and drawings"
authors = ["you"]
edition = "2021"

[lib]
name = "noteberg_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2.11", features = ["wry"] }
tauri-plugin-http = "2"
tauri-plugin-shell = "2"
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"

[target.'cfg(not(target_os = "android"))'.dependencies]
rfd = "0.15"

[target.'cfg(target_os = "windows")'.dependencies]
ureq = "2"
webview2-com = "0.38"
windows-core = "0.61"
windows = { version = "0.58", features = ["Win32_Media_Audio", "Win32_System_Com"] }
keyring = { version = "3", default-features = false, features = ["windows-native"] }
cpal = "0.15"
hound = "3"

[target.'cfg(target_os = "macos")'.dependencies]
keyring = { version = "3", default-features = false, features = ["apple-native"] }

[target.'cfg(target_os = "ios")'.dependencies]
keyring = { version = "3", default-features = false, features = ["apple-native"] }

[target.'cfg(target_os = "linux")'.dependencies]
keyring = { version = "3", default-features = false, features = ["async-secret-service", "async-io", "crypto-rust"] }
