// src/components/overviewMode.test.js
// Covers searchAllNotes' glob matching, specifically its ReDoS fix. The
// original implementation translated glob queries ("*"/"?" wildcards) into a
// regex (escapeRegex(query).replace(/\*/g, ".*")) and ran .test() against
// note content — a run of adjacent ".*" groups against long non-matching
// text is catastrophic-backtracking regex. Confirmed empirically before
// fixing: a 3-wildcard query against 800 characters of non-matching content
// took 41 SECONDS (single-threaded JS, so this froze the whole app, not just
// search); 2 wildcards were already badly non-linear (2000 chars: 3.2s; 4000
// chars: 24s). A wildcard-count cap does not fix this, since 2 adjacent
// wildcards already suffice for exponential blowup — the real fix is the
// linear (non-regex) two-pointer glob scan now used by globQueryMatches/
// wildcardMatch, confirmed here to have no such blowup regardless of
// wildcard count or content length, while preserving the exact old matching
// semantics (case-insensitive, unanchored, "*" = any run of chars incl.
// none, "?" = exactly one char).
//
// This matters more via MCP (mcpBridge.js's search_notes tool) than via the
// UI search box, since a query there can be generated by an LLM rather than
// typed by a person.

import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("../i18n/index.js", () => ({ t: (key) => key }));
vi.mock("../modules/pdfManager.js", () => ({ extractPdfText: vi.fn(() => Promise.resolve("")) }));
vi.mock("../modules/router.js", () => ({ navigateTo: vi.fn() }));

const notesById = new Map();

vi.mock("../modules/storage.js", () => ({
  copyNote: vi.fn(),
  deleteNote: vi.fn(),
  deleteNotebook: vi.fn(),
  getAllNotebooks: vi.fn(() => Promise.resolve([])),
  getAllNotes: vi.fn(() => Promise.resolve([])),
  getDeletedNotebooks: vi.fn(() => Promise.resolve([])),
  getDeletedNotes: vi.fn(() => Promise.resolve([])),
  getNote: vi.fn((id) => Promise.resolve(notesById.get(id) ?? null)),
  getNotebook: vi.fn(),
  getNotesByNotebook: vi.fn(() => Promise.resolve([])),
  getQuickNotes: vi.fn(() => Promise.resolve([...notesById.values()])),
  getSetting: vi.fn(),
  moveNote: vi.fn(),
  purgeNote: vi.fn(),
  purgeNotebook: vi.fn(),
  restoreNote: vi.fn(),
  restoreNotebook: vi.fn(),
}));
vi.mock("../utils/icons.js", () => ({ getIcon: vi.fn(() => "") }));
vi.mock("../utils/noteRenderer.js", () => ({
  drawStroke: vi.fn(),
  getStrokeBounds: vi.fn(),
  getThemePalette: vi.fn(),
  renderNotePreview: vi.fn(),
  renderNoteSnapshot: vi.fn(),
}));
vi.mock("./modals.js", () => ({
  showConfirmDialog: vi.fn(),
  showEditNotebookModal: vi.fn(),
  showEditNoteModal: vi.fn(),
  showMoveCopyDialog: vi.fn(),
}));
vi.mock("./notebookCard.js", () => ({ renderNotebookCard: vi.fn() }));

function setQuickNote(note) {
  notesById.clear();
  notesById.set(note.id, note);
}

describe("searchAllNotes glob matching", () => {
  it("matches a plain substring query, case-insensitively", async () => {
    const { searchAllNotes } = await import("./overviewMode.js");
    setQuickNote({ id: "n1", media: [], content: "Hello World", recognition: null });

    const results = await searchAllNotes("hello");
    expect(results).toHaveLength(1);
    expect(results[0].contentMatch).toBe(true);
  });

  it("supports '*' matching any run of characters", async () => {
    const { searchAllNotes } = await import("./overviewMode.js");
    setQuickNote({
      id: "n1",
      media: [],
      content: "handwriting recognition test",
      recognition: null,
    });

    const results = await searchAllNotes("*hand*recog*");
    expect(results).toHaveLength(1);
  });

  it("supports '?' matching exactly one character", async () => {
    const { searchAllNotes } = await import("./overviewMode.js");
    setQuickNote({ id: "n1", media: [], content: "test1 test2", recognition: null });

    await expect(searchAllNotes("test?")).resolves.toHaveLength(1);
  });

  it("does not match when the query isn't present", async () => {
    const { searchAllNotes } = await import("./overviewMode.js");
    setQuickNote({ id: "n1", media: [], content: "completely unrelated text", recognition: null });

    await expect(searchAllNotes("*nomatch*")).resolves.toHaveLength(0);
  });

  it("matches against recognized handwriting text too", async () => {
    const { searchAllNotes } = await import("./overviewMode.js");
    setQuickNote({
      id: "n1",
      media: [],
      content: "",
      recognition: { fullText: "some scribbled words" },
    });

    const results = await searchAllNotes("scribbled");
    expect(results).toHaveLength(1);
    expect(results[0].recognitionMatch).toBe(true);
  });

  it("no longer rejects many-wildcard queries (the old ReDoS-mitigation cap is gone — the matcher itself is now safe)", async () => {
    const { searchAllNotes } = await import("./overviewMode.js");
    setQuickNote({ id: "n1", media: [], content: "nothing relevant here", recognition: null });

    await expect(searchAllNotes("*a*a*a*a*a*a*a*a*a*a*b")).resolves.toHaveLength(0);
  });
});

describe("globQueryMatches / wildcardMatch (linear glob matcher)", () => {
  it("resolves a many-wildcard query against long non-matching content near-instantly (no catastrophic backtracking)", async () => {
    const { searchAllNotes } = await import("./overviewMode.js");
    setQuickNote({ id: "n1", media: [], content: "a".repeat(20000), recognition: null });

    const start = Date.now();
    const results = await searchAllNotes("*a*a*b"); // 3 wildcards, non-matching — this exact shape took 41s with the old regex at only 800 chars
    const elapsed = Date.now() - start;

    expect(results).toHaveLength(0);
    expect(elapsed).toBeLessThan(500);
  });

  it("still matches correctly against long content when the query does match", async () => {
    const { searchAllNotes } = await import("./overviewMode.js");
    setQuickNote({
      id: "n1",
      media: [],
      content: `${"lorem ipsum ".repeat(1000)}handwriting recognition test${"dolor sit amet ".repeat(1000)}`,
      recognition: null,
    });

    const results = await searchAllNotes("*hand*recog*");
    expect(results).toHaveLength(1);
  });
});

// Note previews are rendered on the fly rather than loaded from a stored
// thumbnail. On slow devices — the Nextcloud app especially — renderNoteSnapshot
// can take seconds, during which the card is blank. A spinner has to cover that
// gap, which means it must be present *before* rendering starts and must be
// cleared afterwards on every path, including failures.
describe("note preview loading spinner", () => {
  // overviewMode.js holds module-level state (the active tab, an incrementing
  // render token) and renderOverview's async tab render can still be in flight
  // when a test ends. Without a fresh module per test, that leaks across tests.
  beforeEach(() => {
    vi.resetModules();
    document.body.innerHTML = "";
  });

  // renderNotePreviews is internal; drive it through the public renderOverview
  // entry point so the real card markup and the real spinner lifecycle run.
  async function renderQuickNotesOverview() {
    const { renderOverview } = await import("./overviewMode.js");
    const container = document.createElement("div");
    document.body.appendChild(container);
    await renderOverview(container);
    return container;
  }

  // renderOverview defers renderNotePreviews to a requestAnimationFrame, so the
  // spinner's pre-render state is observable between those two points.
  function nextAnimationFrame() {
    return new Promise((resolve) => requestAnimationFrame(() => resolve()));
  }

  async function settleAfterAnimationFrame() {
    await nextAnimationFrame();
    // Let renderNotePreviews' async work (getNote + renderNoteSnapshot) drain.
    await new Promise((resolve) => setTimeout(resolve, 0));
  }

  it("shows a spinner on the card before rendering has run", async () => {
    setQuickNote({ id: "n1", media: [], hasStrokes: true, modified: Date.now() });

    const container = await renderQuickNotesOverview();

    expect(container.querySelector(".note-preview-spinner")).not.toBeNull();
  });

  it("places the spinner outside .preview-scaler so the scaler's scale() transform does not shrink it", async () => {
    setQuickNote({ id: "n1", media: [], hasStrokes: true, modified: Date.now() });

    const container = await renderQuickNotesOverview();

    const spinner = container.querySelector(".note-preview-spinner");
    expect(spinner).not.toBeNull();
    expect(spinner.closest(".preview-scaler")).toBeNull();
    expect(spinner.closest(".note-card-preview")).not.toBeNull();
  });

  it("removes the spinner once rendering completes", async () => {
    setQuickNote({ id: "n1", media: [], hasStrokes: true, modified: Date.now() });

    const container = await renderQuickNotesOverview();
    await settleAfterAnimationFrame();

    expect(container.querySelector(".note-preview-spinner")).toBeNull();
  });

  it("removes the spinner even when rendering throws, so a failed card does not spin forever", async () => {
    const { renderNoteSnapshot } = await import("../utils/noteRenderer.js");
    renderNoteSnapshot.mockRejectedValueOnce(new Error("render failed"));
    setQuickNote({ id: "n1", media: [], hasStrokes: true, modified: Date.now() });

    const container = await renderQuickNotesOverview();
    await settleAfterAnimationFrame();

    expect(container.querySelector(".note-preview-spinner")).toBeNull();
  });

  it("clears every card's spinner when one card's render fails, rather than rejecting the whole batch", async () => {
    const { renderNoteSnapshot } = await import("../utils/noteRenderer.js");
    // First card to be rendered throws; the others must still be settled.
    renderNoteSnapshot.mockRejectedValueOnce(new Error("render failed"));
    notesById.clear();
    for (const id of ["n1", "n2", "n3"]) {
      notesById.set(id, { id, media: [], hasStrokes: true, modified: Date.now() });
    }

    const container = await renderQuickNotesOverview();
    expect(container.querySelectorAll(".note-preview-spinner")).toHaveLength(3);

    await settleAfterAnimationFrame();

    expect(container.querySelectorAll(".note-preview-spinner")).toHaveLength(0);
  });

  it("removes the spinner when the note body cannot be loaded", async () => {
    const { getNote } = await import("../modules/storage.js");
    getNote.mockResolvedValueOnce(null);
    setQuickNote({ id: "n1", media: [], hasStrokes: true, modified: Date.now() });

    const container = await renderQuickNotesOverview();
    await settleAfterAnimationFrame();

    expect(container.querySelector(".note-preview-spinner")).toBeNull();
  });

  it("shows no spinner on an empty note, which renders a placeholder instead of a canvas", async () => {
    setQuickNote({
      id: "n1",
      media: [],
      hasStrokes: false,
      hasContent: false,
      modified: Date.now(),
    });

    const container = await renderQuickNotesOverview();

    expect(container.querySelector(".note-preview-canvas")).toBeNull();
    expect(container.querySelector(".note-preview-spinner")).toBeNull();
  });
});
